[theme]
primaryColor="#ff8c42"
backgroundColor="#1a1a1a"
secondaryBackgroundColor="#2d2d2d"
textColor="#ffffff"
font="sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
